# CI de nível 01 - Disparo automático em períodos definidos

# Nome que vai aparecer nas opções de pipe
name: 'Execução Agendada'

# regras de disparo da execução (triggers)
  # gatilho de exec agendada no github actions = schedule

on:
  schedule:
    - cron: '0 14 * * 6'

jobs:

  # descrição do job
  e2e-tests:

    # máquina que o job vai executar
    runs-on: ['ubuntu-latest']
    
    # passo a passo da ações do job
    steps:

      - uses: actions/checkout@v4
      
      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Instalando Playwright
        run: yarn playwright install

      - name: Testes E2E (end-to-end)
        run: yarn run e2e
     
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./playwright-report
