# CI de nível 04 - Disparo dentro do fluxo de CI de desenvolvimento

# Nome que vai aparecer nas opções de pipe
name: 'Execução Integrada'

# regras de disparo da execução (triggers)
# gatilho de exec manual no github actions = workflow_dispatch

on:
  workflow_dispatch:

# inspecao
#	  padronizacao (formatacao de código)
# testes
#	  unidade
#	  e2e
#		  build
# deploy

jobs:
  inspection:
    runs-on: ['ubuntu-latest']

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Padronizacao de codigo (Lint)
        run: yarn lint

  unit:
    runs-on: ['ubuntu-latest']

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Testes de Unidade
        run: yarn run test

  # descrição do job
  e2e-tests:
    # máquina que o job vai executar
    runs-on: ['ubuntu-latest']

    # passo a passo da ações do job
    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Instalando Playwright
        run: yarn playwright install

      - name: Subir aplicacao local
        run: yarn start &

      - name: Testes E2E (end-to-end)
        run: yarn run e2e
        env:
          URL: 'http://localhost:3000'

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./playwright-report
